# Generated by Django 6.1.1 on 2026-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(help_text='Origin location query name', max_length=255)),
                ('destination_name', models.CharField(help_text='Destination location query name', max_length=255)),
                ('travel_mode', models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('driving', 'Driving')], default='cycling', help_text='Modal preference (walking, cycling, driving)', max_length=20)),
                ('route_preference', models.CharField(choices=[('health_first', 'Health First'), ('balanced', 'Balanced'), ('time_first', 'Time First')], default='balanced', help_text='Optimization priority (health_first, balanced, time_first)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when search query was initiated')),
            ],
            options={
                'verbose_name': 'Route Search',
                'verbose_name_plural': 'Route Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
